fruits = ["Apple", "Orange", "Banana"]
print(fruits[0])
print(fruits[1])
print(fruits[2])
print(fruits)
print(len(fruits))
print()
scores = [25, 50, 75, 100]
print(scores[0])
print(scores[1])
print(scores[2])
print(scores[3])
print(scores)
print(len(scores))
print()
person = ["Peter", 25, True]
print(person)
print(person[0])
print(person[1])
print(person[2])
print(len(person))